name: Deploy documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python@3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt install pandoc
        python -m pip install --upgrade pip
        sudo apt-get install -y doxygen
        sudo apt-get install graphviz
        sudo apt-get install python3-sphinx
        pip install sphinx_rtd_theme
        pip install breathe

    - name: Create CMake build environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake -S $GITHUB_WORKSPACE -B . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_DOCS=ON

    - name: Build documentation
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        cmake --build . --target Doxygen -DCMAKE_BUILD_TYPE $BUILD_TYPE
        cmake --build . --target Sphinx -DCMAKE_BUILD_TYPE $BUILD_TYPE
        touch docs/sphinx/.nojekyll

    - name: Deploy documentation
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: ${{runner.workspace}}/build/docs/sphinx # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
